spring:
  application:
    name: laboratorio3
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true



